import { Flex } from '@chakra-ui/react';
import type { GetServerSideProps, NextPage } from 'next';
import { getSession } from 'next-auth/react';
import Head from 'next/head';
import { Hero } from '../components/molecules/hero/hero';
import { LandingBody } from '../components/organisms/landingBody/landingBody';
import { LandingFooter } from '../components/organisms/landingFooter/landingFooter';
import { TopBar } from '../components/organisms/topBar/topBar';
import styles from '../styles/Home.module.css';

const Home: NextPage = () => {
  return (
    <Flex padding="0" height="100vh" flexDirection="column">
      <Head>
        <title>SuperApp</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <TopBar />

      <Flex>
        <Hero />
      </Flex>

      <LandingBody />
      <LandingFooter />
    </Flex>
  );
};

export default Home;

export const getServerSideProps: GetServerSideProps = async ({ req, res }) => {
  const session = await getSession({ req });

  if (session) {
    return {
      redirect: {
        destination: '/logged',
        permanent: false,
      },
    };
  }

  return {
    props: {
      session,
    },
  };
};
